---
- name: Call the playbook run from bastion node to fialover the EDB cluster to Site 1 as the primary. 
  hosts: all
  gather_facts: false
  tasks: 
    - name: Failover EDB cluster to Site 1 as primary/leader. 
      ansible.builtin.shell:
        cmd: tpaexec playbook stagecluster /opt/EDB/TPA/architectures/M1/commands/switchover.yml -e "target=upended"
        chdir: /home/chammer/edb_clusters